Panda\Bundle\CmsBundle\Model\Comment:
    type: entity
    table: comments
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        body:
            type: text
        enabled:
            type: boolean
            options:
               default: true
        createdAt:
            type: datetime
        updatedAt:
            type: datetime

    manyToOne:
        user:
            targetEntity: Panda\Bundle\UserBundle\Model\UserInterface
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: true
        post:
            targetEntity: Panda\Bundle\CmsBundle\Model\PostInterface
            inversedBy: comments
            joinColumn:
                name: post_id
                referencedColumnName: id
                nullable: true


    oneToMany:
        metas:
            targetEntity: Panda\Bundle\CmsBundle\Model\CommentMetaInterface
            mappedBy: post