Panda\Bundle\CmsBundle\Model\PostMeta:
    type: entity
    table: postmetas
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        metaKey:
            type: string

        metaValue:
            type: text

    manyToOne:
        post:
            targetEntity: Panda\Bundle\CmsBundle\Model\PostInterface
            inversedBy: metas
            joinColumn:
                name: post_id
                referencedColumnName: id
                nullable: true
    indexes:
        - {columns: meta_key}