Panda\Bundle\CmsBundle\Model\Post:
    type: entity
    table: posts
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
        body:
            type: text
        enabled:
            type: boolean
            nullable: true
            options:
               default: true
        viewCount:
            type: integer
            nullable: true
            options:
                default: 0
        commentCount:
            type: smallint
        createdAt:
            type: datetime
        updatedAt:
            type: datetime

    manyToOne:
        user:
            targetEntity: Panda\Bundle\UserBundle\Model\UserInterface
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: true
        category:
            targetEntity: Panda\Bundle\CmsBundle\Model\CategoryInterface
            inversedBy: posts
            joinColumn:
                name: category_id
                referencedColumnName: id
                nullable: true
    oneToMany:
        metas:
            targetEntity: Panda\Bundle\CmsBundle\Model\PostMetaInterface
            mappedBy: post