Panda\Bundle\UserBundle\Model\UserMeta:
    type: entity
    table: usermetas
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        metaKey:
            type: string

        metaValue:
            type: text

    manyToOne:
        user:
            targetEntity: Panda\Bundle\UserBundle\Model\UserInterface
            inversedBy: metas
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: true
    indexes:
        - {columns: meta_key}