Panda\Bundle\UserBundle\Model\User:
    type: entity
    table: users
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        avatar:
            type: string
        postCount:
            type: integer
            nullable: true
            options:
                default: 0
        gender:
            type: smallint
        createdAt:
            type: datetime
        updatedAt:
            type: datetime