## FOSUser
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Panda\Bundle\UserBundle\Model\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"